- id: '1579184851262'
  alias: New Automation
  description: ''
  trigger:
  - below: '2'
    entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
    for: 00:02:30
    platform: numeric_state
  - entity_id: binary_sensor.aeotec_limited_zwa005_trisensor_sensor
    for: 00:02:30
    platform: state
    to: 'off'
  condition: []
  action:
  - entity_id: light.sink
    service: light.turn_off
