- id: '1575432903237'
  alias: Laundry Lights On
  description: ''
  trigger:
  - entity_id: binary_sensor.philips_sml001_96c4b704_occupancy
    platform: state
    to: 'on'
  condition:
  - below: '60'
    condition: numeric_state
    entity_id: sensor.philips_sml001_96c4b704_illuminan
  action:
  - alias: ''
    data:
      brightness_pct: 45
      entity_id: group.laundry
    service: light.turn_on
- id: '1575443252163'
  alias: Laundry Lights Off
  description: ''
  trigger:
  - entity_id: binary_sensor.philips_sml001_96c4b704_occupancy
    for: 00:02:30
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: group.laundry
    service: light.turn_off
- id: '1575477726057'
  alias: LIFX Entertainment
  description: ''
  trigger:
  - entity_id: device_tracker.jc_s_iphone
    platform: state
    to: Home
  - event: enter
    platform: geo_location
    source: device_tracker.jc_s_iphone
    zone: zone.home
  condition:
  - after: sunset
    after_offset: 01:00:00
    condition: sun
  action:
  - data:
      entity_id: light.tv
    service: light.turn_on
  - delay: 06:00:00
  - data:
      entity_id: light.tv
    service: light.turn_off
