- id: '1575432903237'
  alias: Laundry Lights On
  description: ''
  trigger:
  - entity_id: binary_sensor.hue_motion_sensor_1_motion
    platform: state
    to: 'on'
  condition:
  - below: '60'
    condition: numeric_state
    entity_id: sensor.hue_motion_sensor_1_light_level
  action:
  - alias: ''
    data:
      brightness_pct: 45
      entity_id: group.laundry
    service: light.turn_on
- id: '1575443252163'
  alias: Laundry Lights Off
  description: ''
  trigger:
  - entity_id: binary_sensor.hue_motion_sensor_1_motion
    for: 00:10:00
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: group.laundry
    service: light.turn_off
- id: '1575477726057'
  alias: LIFX Entertainment
  description: ''
  trigger: []
  condition:
  - after: sunset
    after_offset: '1:00'
    condition: sun
  action:
  - data:
      entity_id: light.tv
    service: light.turn_on
  - delay: 05:00:00
  - data:
      entity_id: light.tv
    service: light.turn_off
- id: '1576165476281'
  alias: Good Morning
  description: ''
  trigger:
  - at: 05:15:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: light.downstairs
    service: light.turn_on
- id: '1576165611736'
  alias: Good Morning Lights Off
  description: ''
  trigger:
  - event: sunrise
    offset: 00:30:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: light.downstairs
    service: light.turn_off
- id: '1576166063742'
  alias: Night On
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      entity_id: light.downstairs
    service: light.turn_on
- id: '1576166148014'
  alias: JC Night On
  description: ''
  trigger:
  - event: sunset
    offset: 01:30:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: light.john
    service: light.turn_on
- id: '1576166316582'
  alias: JC Night Off
  description: ''
  trigger:
  - at: '23:45:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: light.john
    service: light.turn_off
- id: '1576166756372'
  alias: Good Night
  description: ''
  trigger:
  - at: '23:30:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: light.downstairs
    service: light.turn_off
  - data:
      entity_id: light.kitchen
    service: light.turn_off
  - data:
      entity_id: light.upstairs
    service: light.turn_off
