- id: '1581351833841'
  alias: New Automation
  description: ''
  trigger:
  - event: sunset
    offset: 01:30:00
    platform: sun
  condition:
  - condition: state
    entity_id: device_tracker.johns_iphone
    state: home
  action:
  - entity_id: light.john_1
    service: light.turn_on
