- id: '1576707804802'
  alias: LIFX On
  description: ''
  trigger:
  - event: sunset
    offset: '- 00:30:00'
    platform: sun
  condition: []
  action:
  - entity_id: light.tv
    service: light.turn_on
