- id: '1578887993871'
  alias: New Automation
  description: ''
  trigger:
  - above: '2'
    entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
    platform: numeric_state
  condition:
  - below: '40'
    condition: numeric_state
    entity_id: sensor.aeon_labs_zw100_multisensor_6_luminance
  - after: 05:30:00
    before: '23:59:59'
    condition: time
  action:
  - data: {}
    entity_id: light.master_bath_tub_lights
    service: light.turn_on
