
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

mobile_app:

discovery:

lovelace:
  mode: yaml
  
  
                    #################################################
                    #                                               #
                    #               Weather Config                  #
                    #                                               #
                    #################################################

weather:
  platform: darksky
  api_key: a40c3e1df7572a3ab012a99bbbdc677d
  latitude: 39.59644363634748
  longitude: -104.7531521000905
  name: Foxfield CO

                    #################################################
                    #                                               #
                    #               Scene Config                    #
                    #                                               #
                    #################################################
                    

scene:
  - name: Movie Time On
    entities:
      light.man_cave: off
      light.dining: off
      light.upstairs: off
      light.tv: 
        state: on
      
  - name: Movie Time Off
    entities:
      light.man_cave: on
      light.dining: on
      



# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
#   base_url: https://nacnet-ha.duckdns.org:8123
#   ssl_certificate: /ssl/fullchain.pem
#   ssl_key: /ssl/privkey.pem


# Text to speech
tts:
  - platform: google_translate

# Zone Setup
zone:
 
  # This will override the default home zone
  - name: Home
    latitude: 39.596365
    longitude: -104.753233
    radius: 100
    icon: mdi:home



cloud:

lifx:
  light:
    - broadcast: 10.0.25.230
    
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
homeassistant:
  customize: !include customize.yaml
  
# person:
    # - name: John
    #   id: 5afeac34e59d4830907486020e43d175
    #   user_id: ff2822a8b5e04ba89598193e3b31c195
    #   device_trackers:
    #     - device_tracker.jc_s_ip
    # - name: Kim
    #   id: e70f5ba719624cc3a4afecf332755baf
    #   device_trackers:
    #     - device_tracker.kimberly_cernacs_iphone

  

#################################################
#                                               #
#                Nortek USB Setup               #
#                                               #
#################################################

zwave:
    usb_path: /dev/ttyUSB0

zha:
    usb_path: /dev/ttyUSB1
    database_path: zigbee.db