
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

mobile_app:

discovery:



lovelace:
  mode: yaml
  
  
                    #################################################
                    #                                               #
                    #               Weather Config                  #
                    #                                               #
                    #################################################

weather:
  platform: darksky
  api_key: !secret weather_api_key
  latitude: !secret weather_latitude
  longitude: !secret weather_longitude
  name: !secret weather_name


                    #################################################
                    #                                               #
                    #               Homeywell MyTTC                 #
                    #                                               #
                    #################################################

climate:



                    #################################################
                    #                                               #
                    #               Scene Config                    #
                    #                                               #
                    #################################################
                    

# scene:
#   - name: Movie Time On
#     entities:
#       light.man_cave: off
#       light.dining: off
#       light.upstairs: off
#       light.tv: 
#         state: on
      
#   - name: Movie Time Off
#     entities:
#       light.man_cave: on
#       light.dining: on
      

                    #################################################
                    #                                               #
                    #               HACS Sensors                    #
                    #                                               #
                    #################################################


#sensor:  
#  - platform: attributes
#    friendly_name: "Batteries"
#    attribute: battery_level
#    unit_of_measurement: "%"
#    entities:
#      - sensor.hue_motion_sensor_1_light_level

hue:
  bridges:
    - host: 10.0.1.230
      allow_unreachable: true
      allow_hue_groups: false
      


notify:
  - name: My Ecobee
    platform: ecobee

      
frontend:
  themes: !include_dir_merge_named themes/
 

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
#   base_url: https://nacnet-ha.duckdns.org:8123
#   ssl_certificate: /ssl/fullchain.pem
#   ssl_key: /ssl/privkey.pem


# Text to speech
tts:
  - platform: google_translate

# Zone Setup
zone:
 
  # This will override the default home zone
  - name: Home
    latitude: 39.596365
    longitude: -104.753233
    radius: 100
    icon: mdi:home


config:
cloud:
  alexa:
    filter:
      include_entities:
        - group.kitchen
        - group.upstairs
        - group.downstairs
        - group.family_room
        - grouop.stairway
        - group.man_cave
        - group.hallway
        - group.john
        - group.kims_korner
        - group.stove
        - group.upper_hallway
        - group.basement_stairs
        - light.family_1
        - light.family_2
        - light.murano
        - light.sink
        - light.garage_light
        - light.exterior_garage
        - light.office_track
        - light.breakfast_chandelier
        - light.tv
        
      exclude_entities:
        - light.k_1
        - light.k_2
        - light.k_3
        - light.k_4
        - light.k_5
        - light.k_6
        - light.h_1
        - light.h_2
        - light.h3
        - light.h4
        - light.l2
        - light.l1
        - light.man_cave_1
        - light.man_cave_2
        - light.stairway_1
        - light.stairway_2
        - light.stairway_3
        - light.john_1
        - light.john_2
        - light.stove_1
        - light.stove_2
        - light.uh1
        - light.uh2
        - light.uh3
        - light.bs1
        - light.bs2
        - light.bs3
        - light.sengled_z01_cia19nae26_42040403_level_on_off
        - light.sengled_z01_cia19nae26_dca60503_level_on_off
        - group.all_devices
        - group.all_switches
        - group.all_scripts
        - group.all_automations
        - group.someone_home
        - light.caseta_r_wireless_in_wall_dimmer
        - light.caseta_r_wireless_in_wall_dimmer_2
        - light.caseta_r_wireless_in_wall_dimmer_3
        - light.caseta_r_wireless_in_wall_dimmer_4
      exclude_domains:
        - switch
        - automation
        - sensor
        - script
        - binary_sensor
    entity_config:
      group.kitchen:
        name: Kitchen
      group.upstairs:  
        name: Upstairs
      group.downstairs:
        name: Downstairs
      group.family_room:
        name: Family Room
      group.stairway:
        name: Stairway
      group.man_cave:
        name: Man Cave
      group.hallway:
        name: Hallway
      group.upper_hallway:
        name: Upper Hallway
      group.john:
        name: John
      group.kims_korner:
        name: Kim
      group.stove:
        name: Stove
      group.basement_stairs:
        name: Basement Stairs
      light.murano:
        name: Dining
      light.office_1:
        name: Office
      light.sink:
        name: Sink
      light.tv:
        name: Entertainment Light
      light.garage_light:
        name: Garage
      light.exterior_garage:
        name: Garage Outside
      light.office_track:
        name: Office Track
      light.breakfast_chandelier:
        name: Breakfast
          
        
          
# Example configuration.yaml entry
lutron_caseta:
    host: 10.0.1.231
    keyfile: caseta.key
    certfile: caseta.crt
    ca_certs: caseta-bridge.crt

lifx:
  light:
    - broadcast: 10.0.30.230
    

  
person:
    - name: John
      id: 5afeac34e59d4830907486020e43d175
      user_id: ff2822a8b5e04ba89598193e3b31c195
      device_trackers:
        - device_tracker.johns_iphone
    - name: Kim
      id: e70f5ba719624cc3a4afecf332755baf
      device_trackers:
        - device_tracker.kim_iphone


# hue:
#   bridges:
#     - host: 10.0.1.X
#       filename: phue.conf
#       allow_unreachable: true
#       allow_hue_groups: false
  

#################################################
#                                               #
#                Nortek USB Setup               #
#                                               #
#################################################

zwave:
    usb_path: /dev/ttyUSB0

zha:
    usb_path: /dev/ttyUSB1
    database_path: zigbee.db
    

#################################################
#                                               #
#               Includes                        #
#                                               #
#################################################

    
group: !include_dir_merge_named group
automation: !include_dir_merge_list automation
switch: !include_dir_list switches
sensor: !include_dir_merge_list sensors
scene: !include_dir_merge_list scene
timer: !include_dir_merge_named timers
script: !include scripts.yaml
homeassistant:
  customize: !include customize.yaml