resources:
  - url: /local/simple-thermostat.js?v=1
    type: module
    
background: var(--background-image)

title: Home
views:
  - badges:
    #   - entity: binary_sensor.updater
    #   - entity: binary_sensor.motion_sensor_upstair_hall_east_motion
    #   - entity: binary_sensor.motion_sensor_stairway_motion
    #   - entity: binary_sensor.motion_sensor_upstair_hall_west_motion
    #   - entity: binary_sensor.remote_ui
      - entity: person.john
      - entity: person.kim
    #   - entiry: sensor.my_ecobee_temperature
    #  - entity: device_tracker.jc_s_iphone
    #   - entity: sensor.ssid
    #   - entity: sensor.sim_1
    #   - entity: sensor.last_update_trigger
    #   - entity: sensor.floors_descended
    #   - entity: sensor.floors_ascended
    #   - entity: sensor.steps
    #   - entity: sensor.connection_type
    #   - entity: sensor.average_active_pace
    #   - entity: sensor.geocoded_location
    #   - entity: sensor.distance
    #   - entity: sensor.battery_level
    #   - entity: sensor.bssid
    #   - entity: sensor.activity
    #   - entity: sensor.battery_state
    #   - entity: sensor.motion_sensor_stairway_temperature
    #   - entity: sensor.motion_sensor_upstair_hall_west_light_level
    #   - entity: sensor.motion_sensor_upstair_hall_west_temperature
    #   - entity: sensor.motion_sensor_upstair_hall_east_light_level
    #   - entity: sensor.motion_sensor_stairway_light_level
    #   - entity: sensor.motion_sensor_upstair_hall_east_temperature
      - entity: sun.sun
    cards:
      - type: vertical-stack
        cards:
        - type: picture-entity
          entity: group.all_lights
          image: /local/pics/places/havar.jpg
          tap_action:
            action: call-service
            service: light.turn_off
            service_data:
                entity_id: group.all_lights
        - type: horizontal-stack
          cards:
          - type: entity-button
            entity: switch.downstairs
            name: Downstairs
            show_state: true
            icon: "mdi:ceiling-light"
            icon_height: 30px
          - type: entity-button
            entity: switch.upstairs
            name: Upstairs
            show_state: true
            icon: "mdi:ceiling-light"
            icon_height: 30px
        - type: horizontal-stack
          cards:
          - type: entity-button
            entity: switch.man_cave
            name: Man Cave
            show_state: true
            icon: "mdi:lamp"
            icon_height: 30px
          - type: entity-button
            entity: switch.hallway
            name: Hallway
            show_state: true
            icon: "mdi:ceiling-light"
            icon_height: 30px
          - type: entity-button
            entity: light.murano
            name: Murano
            show_state: true
            icon: "mdi:ceiling-light"
            icon_height: 30px
        - type: horizontal-stack
          cards:
          - type: entity-button
            entity: switch.stairway
            name: Stairway
            show_state: true
            icon: "mdi:ceiling-light"
            icon_height: 30px     
          - type: entity-button
            entity: switch.john
            name: John Bed Side
            show_state: true
            icon: 'mdi:lamp'
            icon_height: 30px
          - type: entity-button
            entity: switch.laundry
            name: Laundry
            show_state: true
            icon: "mdi:ceiling-light"
            icon_height: 30px 
        - type: horizontal-stack
          cards:
          - type: entity-button
            entity: switch.family_room
            name: Family Rm
            show_state: true
            icon: "mdi:lamp"
            icon_height: 30px
          - type: entity-button
            entity: light.family_1
            name: Family 1
            show_state: true
            icon: 'mdi:lamp'
            icon_height: 30px
          - type: entity-button
            entity: light.family_2
            name: Family 2
            show_state: true
            icon: "mdi:lamp"
            icon_height: 30px
        - type: horizontal-stack
          cards:
          - type: entity-button
            entity: light.office_1
            name: Office
            show_state: true
            icon: "mdi:desk-lamp"
            icon_height: 30px     
          - type: entity-button
            entity: switch.kitchen
            name: Kitchen
            show_state: true
            icon: "mdi:ceiling-light"
            icon_height: 30px
          - type: entity-button
            entity: switch.stove
            name: Stove
            show_state: true
            icon: "mdi:ceiling-light"
            icon_height: 30px
      - entity:  weather.foxfield_co
        type: weather-forecast
      - type: 'custom:simple-thermostat'
        name: Ecobee
        entity: climate.my_ecobee
        step_size: 1
    icon: 'mdi:home'
    path: default_view
    title: Home

#Scenes Card
  
  - badges: []
    cards:
    - type: vertical-stack
      cards:
      - type: horizontal-stack
        cards:
        - type: entity-button
          entity: scene.movie_time_on
          name: Move Time On
          icon: 'mdi:television'
          icon_height: 45px
          tap_action:
            action: call-service
            service: scene.turn_on
            service_data:
              entity_id: scene.movie_time_on
        - type: entity-button
          entity: scene.movie_time_on
          name: Move Time Off
          icon: 'mdi:television'
          icon_height: 45px
          tap_action:
            action: call-service
            service: scene.turn_on
            service_data:
              entity_id: scene.movie_time_off
      - type: horizontal-stack
        cards:
        - type: entity-button
          entity: light.tv
          name: LIFX TV Backlight
          icon_height: 60px
    icon: 'mdi:television'
    path: scenes
    title: Scenes
    
#Laundry Room Card

  - badges: []
    cards:
      - entities:
          - light.l1
          - light.l2
        show_header_toggle: true
        title: Laundry
        type: entities
      - entities:
          - binary_sensor.laundry_sensor_motion
          - sensor.laundry_sensor_light_level
          - sensor.laundry_sensor_temperature
        show_header_toggle: false
        title: Sensors
        type: entities
      - entities:
          - automation.laundry_lights_off
          - automation.laundry_lights_on
        show_header_toggle: true
        title: Automations
        type: entities
    icon: 'mdi:tumble-dryer'
    path: laundry
    title: Laundry

#Lights Card

  - badges: []
    cards:
      - entities:
          - light.h_1
          - light.h_2
        title: Hallway
        icon: 'mdi:ceiling-light'
        type: entities
      - entities:
          - entity: light.k_1
          - entity: light.k_2
          - entity: light.k_3
          - entity: light.k_4
          - entity: light.k_5
          - entity: light.k_6
        title: Kitchen
        icon: 'mdi:ceiling-light'
        type: entities
      - entities: 
          - entity: light.stove_1
          - entity: light.stove_2
        title: Stove
        icon: 'mdi:ceiling-light'
        type: entities
      - entities:
          - entity: light.family_1
          - entity: light.family_2
        title: Family Room
        icon: 'mdi:lamp'
        type: entities
      - entities:
          - light.man_cave_1
          - light.man_cave_2
          - light.tv
        title: Man Cave
        icon: 'mdi:lamp'
        type: entities
      - entities:
          - light.john_1
          - light.john_2
        title: John
        icon: 'mdi:ceiling-light'
        type: entities
    icon: 'mdi:lightbulb-outline'
    path: lights
    title: Lights

#Automations Card

  - badges: []
    cards:
      - entities:
        - automation.good_morning
        - automation.jc_night_on
        - automation.lifx_entertainment_light_on
        - automation.laundry_lights_on
        - automation.extended_lights_on_a_m
        - automation.night_east_on
        - automation.night_west_on
        show_header_toggle: false
        title: Lights On
        type: entities
      - entities:
        - automation.good_morning_lights_off
        - automation.jc_night_off
        - automation.lifx_entertainment_light_off
        - automation.laundry_lights_off
        - automation.extended_lights_off_a_m
        - automation.good_night
        show_header_toggle: false
        title: Lights Off
        type: entities
    #   - entities:
    #     - automation.lets_test_it
    #     show_header_toggle: false
    #     title: Test Automations
    #     type: entities
    icon: "mdi:cogs"
    path: automations
    title: Automations