
title: Home
views:
  - badges:
    #   - entity: binary_sensor.updater
    #   - entity: binary_sensor.motion_sensor_upstair_hall_east_motion
    #   - entity: binary_sensor.motion_sensor_stairway_motion
    #   - entity: binary_sensor.motion_sensor_upstair_hall_west_motion
    #   - entity: binary_sensor.remote_ui
      - entity: person.john
      - entity: person.kim
      - entity: device_tracker.jc_s_iphone
    #   - entity: sensor.ssid
    #   - entity: sensor.sim_1
    #   - entity: sensor.last_update_trigger
    #   - entity: sensor.floors_descended
    #   - entity: sensor.floors_ascended
    #   - entity: sensor.steps
    #   - entity: sensor.connection_type
    #   - entity: sensor.average_active_pace
    #   - entity: sensor.geocoded_location
    #   - entity: sensor.distance
    #   - entity: sensor.battery_level
    #   - entity: sensor.bssid
    #   - entity: sensor.activity
    #   - entity: sensor.battery_state
    #   - entity: sensor.motion_sensor_stairway_temperature
    #   - entity: sensor.motion_sensor_upstair_hall_west_light_level
    #   - entity: sensor.motion_sensor_upstair_hall_west_temperature
    #   - entity: sensor.motion_sensor_upstair_hall_east_light_level
    #   - entity: sensor.motion_sensor_stairway_light_level
    #   - entity: sensor.motion_sensor_upstair_hall_east_temperature
      - entity: sun.sun
    cards:
      - type: vertical-stack
        cards:
        - type: picture-entity
          entity: group.all_lights
          image: /local/pics/places/havar.jpg
          tap_action:
            action: none
        - type: horizontal-stack
          cards:
          - type: entity-button
            entity: light.downstairs
            name: Downstairs
            show_state: true
            icon_height: 30px
          - type: entity-button
            entity: light.upstairs
            name: Upstairs
            show_state: true
            icon_height: 30px
          - type: entity-button
            entity: light.stairway
            name: Stairway
            show_state: true
            icon_height: 30px
        - type: horizontal-stack
          cards:
          - type: entity-button
            entity: light.office
            name: Office
            show_state: true
            icon: "mdi:desk-lamp"
            icon_height: 30px
          - type: entity-button
            entity: light.hallway
            name: Hallway
            show_state: true
            icon: "mdi:ceiling-light"
            icon_height: 30px
          - type: entity-button
            entity: light.murano
            name: Murano
            show_state: true
            icon: "mdi:ceiling-light"
            icon_height: 30px
        - type: horizontal-stack
          cards:
          - type: entity-button
            entity: light.man_cave
            name: Man Cave
            show_state: true
            icon: "mdi:lamp"
            icon_height: 30px
          - type: entity-button
            entity: light.john
            name: John Bed Side
            show_state: true
            icon: 'mdi:lamp'
            icon_height: 30px
          - type: entity-button
            entity: light.kitchen
            name: Kitchen
            show_state: true
            icon: "mdi:ceiling-light"
            icon_height: 30px
        - type: horizontal-stack
          cards:
          - type: entity-button
            entity: light.family_room
            name: Family Rm
            show_state: true
            icon: "mdi:lamp"
            icon_height: 30px
          - type: entity-button
            entity: light.family_1
            name: Family 1
            show_state: true
            icon: 'mdi:lamp'
            icon_height: 30px
          - type: entity-button
            entity: light.family_2
            name: Family 2
            show_state: true
            icon: "mdi:lamp"
            icon_height: 30px
      - entity:  weather.foxfield_co
        type: weather-forecast
    icon: 'mdi:home'
    path: default_view
    title: Home
  - badges: []
    cards:
    - type: vertical-stack
      cards:
      - type: horizontal-stack
        cards:
        - type: entity-button
          entity: scene.movie_time_on
          name: Move Time On
          icon: 'mdi:television'
          icon_height: 45px
          tap_action:
            action: call-service
            service: scene.turn_on
            service_data:
              entity_id: scene.movie_time_on
        - type: entity-button
          entity: scene.movie_time_on
          name: Move Time Off
          icon: 'mdi:television'
          icon_height: 45px
          tap_action:
            action: call-service
            service: scene.turn_on
            service_data:
              entity_id: scene.movie_time_off
      - type: horizontal-stack
        cards:
        - type: entity-button
          entity: light.tv
          name: LIFX TV Backlight
          icon_height: 60px
    icon: 'mdi:television'
    path: scenes
    title: Scenes
  - badges: []
    cards:
      - entities:
          - light.sengled_z01_cia19nae26_42040403_level_on_off
          - light.sengled_z01_cia19nae26_dca60503_level_on_off
        show_header_toggle: true
        title: Lights
        type: entities
      - entities:
          - binary_sensor.philips_sml001_96c4b704_occupancy
          - sensor.philips_sml001_96c4b704_illuminan
          - sensor.philips_sml001_96c4b704_power
          - sensor.philips_sml001_96c4b704_temperature
        show_header_toggle: false
        title: Sensors
        type: entities
      - entities:
          - automation.laundry_lights_off
          - automation.laundry_lights_on
        show_header_toggle: true
        title: Automations
        type: entities
    icon: 'mdi:tumble-dryer'
    path: laundry
    title: Laundry
  - badges: []
    cards:
      - entities:
          - light.h_1
          - light.h_2
        title: Hallway
        icon: 'mdi:ceiling-light'
        type: entities
      - entities:
          - entity: light.k_1
          - entity: light.k_2
          - entity: light.k_3
          - entity: light.k_4
          - entity: light.k_5
          - entity: light.k_6
        title: Kitchen
        icon: 'mdi:ceiling-light'
        type: entities
      - entities: 
          - entity: light.stove_1
          - entity: light.stove_2
        title: Stove
        icon: 'mdi:ceiling-light'
        type: entities
      - entities:
          - entity: light.family_1
          - entity: light.family_2
        title: Family Room
        icon: 'mdi:lamp'
        type: entities
      - entities:
          - light.man_cave_1
          - light.man_cave_2
          - light.tv
        title: Man Cave
        icon: 'mdi:lamp'
        type: entities
      - entities:
          - light.john_1
          - light.john_2
        title: John
        icon: 'mdi:ceiling-light'
        type: entities
    icon: 'mdi:lightbulb-outline'
    path: lights
    title: Lights
  - badges: []
    cards:
      - entities:
        - automation.lifx_entertainment
        - automation.laundry_lights_off
        - automation.laundry_lights_on
        title: Automation
        type: entities     
    icon: "mdi:cogs"
    path: automations
    title: Automations