- alias: Leaving Daytime
  trigger:
  - entity_id: sensor.home_presence
    from: "home"
    platform: state
    to: "not_home"
  condition:
  - condition: sun
    after: sunrise
    before: sunset
    before_offset: "-00:45:00"
  action:
    - service: light.turn_off
      data:
        entity_id: group.all_lights
    - service: climate.set_preset_mode
      data:
        entity_id: climate.my_ecobee
        preset_mode: 'away'