- alias: Leaving Daytime
  trigger:
  - entity_id: sensor.home_presence
    from: "home"
    platform: state
    to: "not_home"
  condition:
  - condition: sun
    after: sunrise
    before: sunset
    before_offset: "-00:45:00"
  action:
    - entity_id: all
      service: light.turn_off
    - entity_id: climate.my_ecobee
      service: climate.set_preset_mode
      data:
        preset_mode: 'away'