- alias: Leaving Daytime
  trigger:
  - entity_id: sensor.home_presence
    from: "home"
    platform: state
    to: "not_home"
  condition:
  - condition: sun
    after: sunrise
    before: sunset
    before_offset: "-00:45:00"
  action:
  - data:
      entity_id: group.all_lights
    service: light.turn_off