- alias: Leaving After Sunset
  trigger:
  - entity_id: sensor.home_presence
    from: "home"
    platform: state
    to: "not_home"
  condition:
  - condition: sun
    after: sunset
    after_offset: "00:30:00"
  action:
    service: homeassistant.turn_off
    data:
      entity_id: 
        - light.family_2
        - light.sink
        - light.office_1        
        - switch.kitchen
        - switch.upstairs
        - switch.laundry
        - switch.hallway
        - switch.upper_hallway
        - switch.basement_stairs
